<a href="https://colab.research.google.com/github/charleslbryant/AdminLTE/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

Following Learn PyTorch
https://www.learnpytorch.io/

https://www.youtube.com/watch?v=Z_ikDlimN6A&t=5865s&ab_channel=DanielBourke




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


#Tensors

Tensors are a way to represent data especially multidimensional data. 

`torch.tensors` is a multi-dimensional matrix containing elements of a single type..

https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar tensor
# [7]
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [10]:
# Vector

vector = torch.tensor([3,4])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [22]:
# MATRIX

MATRIX = torch.tensor([[3,5]])
MATRIX

tensor([[3, 5]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([1, 2])

In [17]:
MATRIX[0]

tensor([3, 5])

In [19]:
MATRIX.size()

torch.Size([1, 2])

In [21]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
# Random Tensor

# Start with random number > Look at data > Update random numbers > Look at data > Update...

# Create random tensor with size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2590, 0.1487, 0.6910, 0.4693],
        [0.0408, 0.5622, 0.2906, 0.2498],
        [0.4338, 0.7451, 0.0160, 0.3231]])