<a href="https://colab.research.google.com/github/charleslbryant/AdminLTE/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

Following Learn PyTorch
https://www.learnpytorch.io/

https://www.youtube.com/watch?v=Z_ikDlimN6A&t=5865s&ab_channel=DanielBourke




In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


#Tensors

Tensors are a way to represent data especially multidimensional data. 

`torch.tensors` is a multi-dimensional matrix containing elements of a single type..

https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar tensor
# [7]
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector

vector = torch.tensor([3,4])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[3,5]])
MATRIX

tensor([[3, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([1, 2])

In [13]:
MATRIX[0]

tensor([3, 5])

In [14]:
MATRIX.size()

torch.Size([1, 2])

In [15]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
# Random Tensor

# Neural networks - Start with random number > Look at data > Update random numbers > Look at data > Update...

# Create random tensor with size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.0986, 0.9200, 0.1376, 0.9396],
        [0.3631, 0.8813, 0.7935, 0.5035],
        [0.0451, 0.9489, 0.0101, 0.9005]])

In [20]:
# Create a mask with a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros.dtype

torch.float32

In [29]:
# Range

range = torch.arange(start=2, end=40, step=7)
range

tensor([ 2,  9, 16, 23, 30, 37])

In [24]:
torch.__version__

'1.12.1+cu113'

In [32]:
ten_zeros = torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

In [34]:
# Tensor Constructor
# dtype = tensor data type, select lowest bit data type to reduce memory usage
#   when working with tensors. Default is Float 32.
# device = type of device used, CPU, cuda
# requires_grad = requires gradient tracking across tensor operations

float_32_tensor = torch.tensor([3.0,6,0,9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 0., 9.])

In [37]:
# Get datatype
float_32_tensor.dtype

torch.float32

In [39]:
# Get size or shape

float_32_tensor.size()

torch.Size([4])

In [38]:
# Get shape or size

float_32_tensor.shape

torch.Size([4])

In [40]:
float_32_tensor.device

device(type='cpu')